name: Kubernetes CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  validate:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install kubeconform
        run: |
          wget https://github.com/yannh/kubeconform/releases/latest/download/kubeconform-linux-amd64.tar.gz
          tar xf kubeconform-linux-amd64.tar.gz
          sudo mv kubeconform /usr/local/bin

      - name: Validate Kubernetes Manifests
        run: |
          kubeconform -summary manifests/*.yaml